# Generated by Django 5.2.11 on 2026-10-02 10:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='Student ID')),
                ('first_name', models.CharField(max_length=60, verbose_name='First name')),
                ('last_name', models.CharField(max_length=60, verbose_name='Last name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number, e.g. +1 555 123 4567.', regex='^\\+?[\\d\\s\\-().]{7,20}$')], verbose_name='Phone')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('address', models.CharField(max_length=255, verbose_name='Street address')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='State / Province')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Postal code')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Country')),
                ('course', models.CharField(blank=True, max_length=120, verbose_name='Course / Program')),
                ('department', models.CharField(blank=True, max_length=120, verbose_name='Department')),
                ('enrollment_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Enrollment year')),
                ('is_active', models.BooleanField(default=True, verbose_name='Currently enrolled')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'students',
                'ordering': ['-created_at'],
            },
        ),
    ]
